pipeline {
    agent any

    tools {
        maven 'mvn'
        jdk 'jdk17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/HiwalePriyanka94/Capstone_Project.git'
            }
        }

        stage('Build') {
            steps {
                dir('BoardGame') {
                    sh 'mvn -N io.takari:maven:wrapper'
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('BoardGame') {
                    sh './mvnw test'
                }
            }
        }

        stage('Security Scan') {
            steps {
                dir('BoardGame') {
                    sh './mvnw sonar:sonar -Dsonar.projectKey=BoardGame'
                }
                sh 'trivy fs .'
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    def app = docker.build("boardgame:latest", "./BoardGame")
                    app.push()
                }
            }
        }

        stage('Deploy to AWS') {
            steps {
                sh 'terraform init'
                sh 'terraform apply -auto-approve'
                sh 'ansible-playbook deploy.yml'
            }
        }

        stage('Smoke Test') {
            steps {
                sh 'curl -f http://<frontend-alb-dns>/ || echo "Frontend test failed"'
                sh 'curl -f http://<backend-alb-dns>/api/tasks || echo "Backend test failed"'
            }
        }
    }
}

